# Generated by Django 3.0.6 on 2020-06-10 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200610_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name_plural': 'Videos'},
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='title',
            new_name='name',
        ),
    ]
